# Set the message here
message = "ğŸ˜€LOLâ¤"
# Control the brightness here
intensity = 5
# Github username, as it appears in your profile's URL: https://github.com/<githubUser>
githubUser = "yourGithubUsername"

# other stuff
repoName = "dummy-repo-github-graphiti"
localRepoDir = "/tmp"
isPreview = false # Set to true to preview the message without pushing to github

